// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecureVideoStreaming.Data.Context;

#nullable disable

namespace SecureVideoStreaming.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251207222250_AddPublicKeyFingerprintToUser")]
    partial class AddPublicKeyFingerprintToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SecureVideoStreaming.Models.Entities.AccessLog", b =>
                {
                    b.Property<long>("IdRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRegistro"));

                    b.Property<string>("DireccionIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DuracionAcceso")
                        .HasColumnType("int");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaHoraAcceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("IdVideo")
                        .HasColumnType("int");

                    b.Property<string>("MensajeError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoAcceso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdRegistro");

                    b.HasIndex("FechaHoraAcceso");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdVideo");

                    b.HasIndex("TipoAcceso");

                    b.ToTable("RegistroAccesos", (string)null);
                });

            modelBuilder.Entity("SecureVideoStreaming.Models.Entities.CryptoData", b =>
                {
                    b.Property<int>("IdDatoCripto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDatoCripto"));

                    b.Property<byte[]>("AAD")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("AlgoritmoKEK")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("ChaCha20-Poly1305");

                    b.Property<byte[]>("AuthTag")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varbinary(16)");

                    b.Property<DateTime>("FechaGeneracionClaves")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<byte[]>("HMACDelVideo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varbinary(64)");

                    b.Property<byte[]>("HashSHA256Original")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<int>("IdVideo")
                        .HasColumnType("int");

                    b.Property<byte[]>("KEKCifrada")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varbinary(12)");

                    b.Property<string>("VersionAlgoritmo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("1.0");

                    b.HasKey("IdDatoCripto");

                    b.HasIndex("IdVideo")
                        .IsUnique();

                    b.ToTable("DatosCriptograficosVideos", (string)null);
                });

            modelBuilder.Entity("SecureVideoStreaming.Models.Entities.Permission", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermiso"));

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaOtorgamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaRevocacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("IdVideo")
                        .HasColumnType("int");

                    b.Property<int?>("MaxAccesos")
                        .HasColumnType("int");

                    b.Property<int>("NumeroAccesos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("OtorgadoPor")
                        .HasColumnType("int");

                    b.Property<int?>("RevocadoPor")
                        .HasColumnType("int");

                    b.Property<string>("TipoPermiso")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Lectura");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.HasKey("IdPermiso");

                    b.HasIndex("FechaExpiracion");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdVideo");

                    b.HasIndex("OtorgadoPor");

                    b.HasIndex("RevocadoPor");

                    b.HasIndex("TipoPermiso");

                    b.HasIndex("IdVideo", "IdUsuario")
                        .IsUnique();

                    b.ToTable("Permisos", (string)null);
                });

            modelBuilder.Entity("SecureVideoStreaming.Models.Entities.User", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ClavePublicaRSA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varbinary(64)");

                    b.Property<string>("PublicKeyFingerprint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("TipoUsuario");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("SecureVideoStreaming.Models.Entities.UserKeys", b =>
                {
                    b.Property<int>("IdClaveUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClaveUsuario"));

                    b.Property<byte[]>("ClaveHMAC")
                        .HasMaxLength(64)
                        .HasColumnType("varbinary(64)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("FingerprintClavePublica")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdClaveUsuario");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ClavesUsuarios", (string)null);
                });

            modelBuilder.Entity("SecureVideoStreaming.Models.Entities.Video", b =>
                {
                    b.Property<int>("IdVideo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVideo"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Duracion")
                        .HasColumnType("int");

                    b.Property<string>("EstadoProcesamiento")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Procesando");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSubida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FormatoVideo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdAdministrador")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivoCifrado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombreArchivoOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RutaAlmacenamiento")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("TamañoArchivo")
                        .HasColumnType("bigint");

                    b.Property<string>("TituloVideo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdVideo");

                    b.HasIndex("EstadoProcesamiento");

                    b.HasIndex("FechaSubida");

                    b.HasIndex("IdAdministrador");

                    b.HasIndex("NombreArchivoCifrado")
                        .IsUnique();

                    b.ToTable("Videos", (string)null);
                });

            modelBuilder.Entity("SecureVideoStreaming.Models.Entities.AccessLog", b =>
                {
                    b.HasOne("SecureVideoStreaming.Models.Entities.User", "Usuario")
                        .WithMany("RegistrosAccesos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SecureVideoStreaming.Models.Entities.Video", "Video")
                        .WithMany("RegistrosAccesos")
                        .HasForeignKey("IdVideo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("SecureVideoStreaming.Models.Entities.CryptoData", b =>
                {
                    b.HasOne("SecureVideoStreaming.Models.Entities.Video", "Video")
                        .WithOne("DatosCriptograficos")
                        .HasForeignKey("SecureVideoStreaming.Models.Entities.CryptoData", "IdVideo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("SecureVideoStreaming.Models.Entities.Permission", b =>
                {
                    b.HasOne("SecureVideoStreaming.Models.Entities.User", "Usuario")
                        .WithMany("Permisos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SecureVideoStreaming.Models.Entities.Video", "Video")
                        .WithMany("Permisos")
                        .HasForeignKey("IdVideo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecureVideoStreaming.Models.Entities.User", "UsuarioOtorgante")
                        .WithMany()
                        .HasForeignKey("OtorgadoPor")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SecureVideoStreaming.Models.Entities.User", "UsuarioRevocador")
                        .WithMany()
                        .HasForeignKey("RevocadoPor")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioOtorgante");

                    b.Navigation("UsuarioRevocador");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("SecureVideoStreaming.Models.Entities.UserKeys", b =>
                {
                    b.HasOne("SecureVideoStreaming.Models.Entities.User", "Usuario")
                        .WithMany("ClavesUsuarios")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SecureVideoStreaming.Models.Entities.Video", b =>
                {
                    b.HasOne("SecureVideoStreaming.Models.Entities.User", "Administrador")
                        .WithMany("VideosAdministrados")
                        .HasForeignKey("IdAdministrador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Administrador");
                });

            modelBuilder.Entity("SecureVideoStreaming.Models.Entities.User", b =>
                {
                    b.Navigation("ClavesUsuarios");

                    b.Navigation("Permisos");

                    b.Navigation("RegistrosAccesos");

                    b.Navigation("VideosAdministrados");
                });

            modelBuilder.Entity("SecureVideoStreaming.Models.Entities.Video", b =>
                {
                    b.Navigation("DatosCriptograficos");

                    b.Navigation("Permisos");

                    b.Navigation("RegistrosAccesos");
                });
#pragma warning restore 612, 618
        }
    }
}
